git:
  tags: @git.tags@
  branch: @git.branch@
  remote:
    origin:
      url: @git.remote.origin.url@
  commit:
    id:
      abbrev: @git.commit.id.abbrev@
      describe: @git.commit.id.describe@
    user:
      name: @git.commit.user.name@
    message:
      short: @git.commit.message.short@
    time: @git.commit.time@

info:
  app:
    name: Otchi
    description: Food network
    version: @git.commit.time@.@git.commit.id.abbrev@

spring:
    social:
        redirectAfterSignInUrl: "/#/feed"
    http:
        multipart:
          max-file-size: 10MB
liquibase:
    contexts: test
    change-log: classpath:/database/db.changelog-master.xml
multipart:
   enabled: true

otchi:
   mail:
      noReply: "noreply@otchi.io"
   user:
      default-picture: "/assets/images/unknown_user.png"
   websocket:
         channel:
            notifications: "/topic/notifications"
server:
  port: 8080
